### PR TITLE
fix: create clip api method and change response type

### LINKED ISSUE #496: Incorrect HTTP method for clips endpoint
Hey, wanting to hook up something that relies on creating clips, but it looks like the CreateClipRequest introduced in #343  is using a GET request instead of a POST request like the documentation mentions https://dev.twitch.tv/docs/api/reference/#create-clip

I couldn't see any other PRs for this already so I'm happy to write up the changes and open one if its not on anyones roadmap :)

### PR DESCRIPTION
**Pull request by jacobtread**
## Description

Updates the create-clip API to use the POST method instead of GET along with some minor docs updates 

## Changes

- Updates the create-clip request to use the POST method
- Align the documentation with the latest current Twitch documentation

## Related Issues

- Closes #496

### CODE REVIEW

File: src/helix/endpoints/clips/create_clip.rs [hunk 1]
```diff
@@ -12,9 +12,9 @@
 //! let request = create_clip::CreateClipRequest::broadcaster_id("1234");
 //! ```
 //!
-//! ## Response: [CreatedClip]
+//! ## Response: [Vec<CreatedClip>]
```
Comment (Nerixyz) [inline src/helix/endpoints/clips/create_clip.rs:15]:
```suggestion
//! ## Response: [CreatedClip]
```

We always link to the item that is returned. Moreover, `[Vec<CreatedClip>]` is invalid markdown (rustdoc also complains about this).

**Comment by Nerixyz** [comment]
> The twitch API documentation here specifies that the response is an array

Yea, all responses from Twitch are arrays (not sure why).

> Not sure if you have any way built into your response handling to transform that?

We have [`parse_single_return`](https://github.com/twitch-rs/twitch_api/blob/7e676ec3c1c42aaab3c3baf03e905440aea9aed3/src/helix/request.rs#L440-L470) for this.

**Comment by Emilgardis** [comment]
Could we change the response type in the `impl Response` to just be `CreatedClip`, this change will need a bump anyway. See for example https://github.com/twitch-rs/twitch_api/blob/7e676ec3c1c42aaab3c3baf03e905440aea9aed3/src/helix/endpoints/users/update_user.rs#L94 for how to do it

**Comment by jacobtread** [comment]
I have updated it to use the parse_single_return :)

**Review by Nerixyz — APPROVED** [review]
LGTM
